'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

import { AuthRequired } from '../components/auth-required';
import { apiFetch, type WorkflowNotification } from '../lib/api-client';

export default function WorkflowNotificationsPage() {
  const [notifications, setNotifications] = useState<WorkflowNotification[]>(
    [],
  );
  const [message, setMessage] = useState('Loading...');

  useEffect(() => {
    async function load() {
      try {
        const response = await apiFetch<WorkflowNotification[]>(
          '/workflow-notifications',
        );
        setNotifications(response.data);
        setMessage('Loaded.');
      } catch (error) {
        setMessage(error instanceof Error ? error.message : 'Load failed');
      }
    }
    void load();
  }, []);

  return (
    <AuthRequired>
      <section className="stack">
        <div className="hero">
          <p className="eyebrow">Workflow Engine</p>
          <h1>Workflow Notifications</h1>
          <p>Database notification records generated by workflow actions.</p>
        </div>
        <section className="panel">
          <p>{message}</p>
          <table className="table">
            <thead>
              <tr>
                <th>Type</th>
                <th>Title</th>
                <th>Document</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              {notifications.map((notification) => (
                <tr key={notification.id}>
                  <td>{notification.type}</td>
                  <td>
                    <strong>{notification.title}</strong>
                    <br />
                    <small>{notification.message}</small>
                  </td>
                  <td>
                    {notification.document ? (
                      <Link href={`/documents/${notification.document.id}`}>
                        {notification.document.referenceNumber}
                      </Link>
                    ) : (
                      'n/a'
                    )}
                  </td>
                  <td>{new Date(notification.createdAt).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      </section>
    </AuthRequired>
  );
}
