export {
  DocumentConfidentiality,
  DocumentPriority,
  DocumentRouteAction,
  DocumentStatus,
  DocumentTimelineAction,
  OrganizationStatus,
  Prisma,
  PrismaClient,
  UserStatus,
  WorkflowConditionOperator,
  WorkflowHistoryAction,
  WorkflowInstanceStatus,
  WorkflowNotificationType,
  WorkflowTaskStatus,
} from '@prisma/client';

export type {
  AuditLog,
  Department,
  Document,
  DocumentAttachment,
  DocumentRoute,
  DocumentTimelineEvent,
  Organization,
  Permission,
  Role,
  RolePermission,
  Session,
  User,
  Workflow,
  WorkflowAssignment,
  WorkflowDelegation,
  WorkflowHistoryEvent,
  WorkflowInstance,
  WorkflowNotification,
  WorkflowStep,
  WorkflowTask,
  WorkflowVersion,
} from '@prisma/client';
